# Generated by Django 5.0.2 on 2024-03-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "servings_consumed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount consumed in servings",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("calories", models.DecimalField(decimal_places=2, max_digits=6)),
                ("fat", models.DecimalField(decimal_places=2, max_digits=5)),
                ("carbs", models.DecimalField(decimal_places=2, max_digits=5)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "serving_size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Serving size in grams",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="dietlog",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AddField(
            model_name="dietlog",
            name="entries",
            field=models.ManyToManyField(to="diet.dietlogentry"),
        ),
        migrations.AddField(
            model_name="dietlogentry",
            name="food_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diet.fooditem"
            ),
        ),
    ]
