# Generated by Django 5.0.2 on 2024-03-02 00:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0003_dietlog_user_dietlogentry_user_fooditem_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DietLog",
            new_name="UserDietLog",
        ),
        migrations.RenameModel(
            old_name="DietLogEntry",
            new_name="UserDietLogEntry",
        ),
        migrations.RenameModel(
            old_name="FoodItem",
            new_name="UserFoodItem",
        ),
    ]
