# Generated by Django 5.0.2 on 2024-03-02 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0004_rename_dietlog_userdietlog_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdietlog",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="userfooditem",
            options={"ordering": ["name"]},
        ),
    ]
