# Generated by Django 5.0.2 on 2024-03-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkout",
            name="one_rep_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="userworkout",
            name="one_set_max_reps",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="userworkout",
            name="weight",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="percentage_of_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="rpe",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
