# Generated by Django 5.0.2 on 2024-03-03 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkout",
            name="percentage_of_max",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userworkout",
            name="rpe",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="primary_target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_target",
                to="workout.userbodypart",
            ),
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="secondary_targets",
            field=models.ManyToManyField(
                blank=True, related_name="secondary_target", to="workout.userbodypart"
            ),
        ),
    ]
