# Generated by Django 5.0.2 on 2024-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0002_userworkout_percentage_of_max_userworkout_rpe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkout",
            name="is_user_added",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userworkout",
            name="exercise_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
