# Generated by Django 5.0.2 on 2024-03-02 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("steps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersteps",
            options={"ordering": ["-date"]},
        ),
    ]
