# Generated by Django 5.0.2 on 2024-03-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streak", "0002_rename_streak_userstreak_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userstreak",
            options={"ordering": ["-last_update_date"]},
        ),
        migrations.AddField(
            model_name="userstreak",
            name="higher_casual_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstreak",
            name="higher_super_streak",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
