# Generated by Django 5.0.2 on 2024-03-03 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("streak", "0003_alter_userstreak_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstreak",
            old_name="higher_casual_streak",
            new_name="highest_casual_streaks",
        ),
        migrations.RenameField(
            model_name="userstreak",
            old_name="higher_super_streak",
            new_name="highest_super_streaks",
        ),
    ]
