# Generated by Django 5.0.2 on 2024-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "streak",
            "0004_rename_higher_casual_streak_userstreak_highest_casual_streaks_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstreakrecord",
            name="streak_type",
            field=models.CharField(
                choices=[("all", "Super Streaks"), ("casual", "Casual")], max_length=20
            ),
        ),
    ]
