# Generated by Django 5.0.2 on 2024-03-03 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("level", "0002_alter_record_options_alter_record_experience_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="UserRecord",
        ),
    ]
