# Generated by Django 5.0.2 on 2024-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sex",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default=0,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
