# Generated by Django 5.0.2 on 2024-03-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userprofile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
