name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker images
        run: |
          docker build -t mydockerhubusername/backend backend/
          docker build -t mydockerhubusername/frontend frontend/

      - name: Run Django tests
        run: |
          docker run mydockerhubusername/backend python manage.py test

      - name: Build React Native app
        run: |
          cd frontend/ && npm install && npx react-native build

      - name: Publish Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push mydockerhubusername/backend
          docker push mydockerhubusername/frontend
