# Generated by Django 5.0.2 on 2024-03-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("happiness", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="happinessslog",
            name="date",
            field=models.DateField(),
        ),
    ]
