# Generated by Django 5.0.2 on 2024-03-03 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("happiness", "0006_alter_userhappinessslog_happiness_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserHappinesssLog",
            new_name="UserHappinessLog",
        ),
    ]
